config/routes.rb
Rails.application.routes.draw do
  get 'photos/index'
  devise_for :users
  devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  get "home/about"
  
  resources :albums do
    resources :photos do
      resources :tags
    end
  end
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/album.rb
class Album < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 4 }
  belongs_to :user
  has_many :photos, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  validates :photo, presence: true
  validates :name, presence: true
  validates :all_tags, presence: true
  belongs_to :album
  has_one_attached :photo
  has_many :taggings, dependent: :destroy
  has_many :tags , through: :taggings

  def photos
    return self.photo.variant(resize: "300x280")
  end

  def all_tags=(names)
    self.tags = names.split(',').map do |name|
      Tag.where(name: name).first_or_create!
    end
  end
  def all_tags
    tags.map(&:name).join(", ")
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings ,dependent: :destroy
  has_many :photos, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :photo
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :albums
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums = Album.all
  end

  def show
    
    @album = Album.find(params[:id])
  end

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)
    

    if @album.save!
      redirect_to albums_path
    else
      render :new
    end
  end

  def edit
    @album = Album.find(params[:id])
  end

  def update
    @album = Album.find(params[:id])

    if @album.update(album_params)
      redirect_to albums_path
    else
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    
    redirect_to albums_path
  end

  private
    def album_params
      params.require(:album).permit(:name, :description, :user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def new
      @photo = Photo.new
  end
  def create
      @album = Album.find(params[:album_id])
      @photos = @album.photos.create(photo_params)
      if @photo.save
          redirect_to album_path(id: @album.id)
      end
  end

  def destroy
      @album = Album.find(params[:id])
      @photo = @album.photos.find(params[:album_id])
      @photo.destroy
      redirect_to album_path
  end


  private
  def photo_params
      params.permit(:photo, :name, :all_tags)
  end

end

app/helpers/album_helper.rb
module AlbumHelper
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/albums/_form.html.erb
<%= form_with model: @album  do |form| %>
  <div>
        <%= form.label :name %><br>
        <%= form.text_field :name %>
        <% @album.errors.full_messages_for(:name).each do |message| %>
        <div><%= message %></div>
        <% end %>
  </div>

  <div>
        <%= form.label :description %><br>
        <%= form.text_area :description %>
        <% @album.errors.full_messages_for(:description).each do |message| %>
        <div><%= message %></div>
        <% end %>
  </div>

  <div>
        
        <%= form.number_field :user_id, id: :album_user_id , value: current_user.id ,type: :hidden%>
        <% @album.errors.full_messages_for(:user_id).each do |message| %>
        <div><%= message %></div>
        <% end %>
  </div><hr>
  <div>
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Edit album</h1>

<%= render "form", album: @album %>

app/views/albums/index.html.erb
<h1>Albums</h1>
<div class="containers text-white p-2 rounded-3">
  
      <% @albums.each do |album| %>
      <% if album.user == current_user %>
<table class="table table-hover">

  <tbody>

    <tr>

      <td class="col-9"><%= album.name%></td>
      <td><%= link_to "Show", album_path(album)%></td>
      <td><%= link_to "Edit", edit_album_path(album)%></td>
      <td><%= link_to "Delete Album" , album_path(album),  :method => :delete,data: { confirm: "Are you sure?" } %></td>
<tr>

</tbody>
</table>

  <% end %>
    <% end %>

app/views/albums/new.html.erb
<div class="bg-light p-3 rounded-3">
<h1>Add New Album</h1>
<%= render "form", album: @album %>
</div>
<div class="fw-bold"><%= link_to "Back" , albums_path%></div>

app/views/albums/show.html.erb
<h4><%= @album.name %></h4>
<div class="bg-light p-4">


<div class="row">
 <div class="col-12">
 <%= @album.description %>
 </div>

<div class="col-12 d-flex justify-content-end">
<%= link_to "Edit", edit_album_path(@album) ,class:"btn btn-primary p-2" %></li>
<%= link_to "Delete", album_path(@album),class:"btn btn-dark ms-2" ,
                   :method => :delete,data: { confirm: "Are you sure?" }  %></li>
</div>

</div>



</div>


  <%= form_with url: album_photos_path(album_id: @album.id)  do |form| %>

  <div class= "row bg-dark bd-dark text-white rounded-3 p-2">
    <h4>Add a Photo</h4>
    <hr>
  <div class="col-12 mt-1 w-50">
          <%= form.file_field :photo %>
          </div>
         <div class= "col-12 mt-2">
          <%= form.label :"Name" %><br />
          <%= form.text_field :name %></div>

          <div class= "col-12 mt-2">
          <%= form.label :"Add Tags" %><br />
          <%= form.text_field :all_tags%></div> 
          <div class= "col-12 mt-2">
          <%= form.submit class: ' btn-primary rounded-3' %></div>
          </div>
  <% end %>



<div class="container p-3 rounded-3">
<h2 class="col-12 d-flex justify-content-center">Photos<h2>

<% @album.photos.each do |photo| %>
      <p>
        <%= image_tag(photo.photos)%>
      </p>

      <h5>Photo:<%= photo.name%></h5>
      <h6>Tags: <%= photo.all_tags%></h5>  
      <h5>
        <%= link_to "Delete",album_photo_path(photo), class:"btn btn-dark",  :method => :delete,data: { confirm: "Are you sure?" } %>
      </h5> 
<% end %>
<hr>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  <%= link_to "Album App" , root_path , class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">

        <% if user_signed_in? %>   
        
        <li class="nav-item">
           <%= link_to "Albums" , albums_path , class:"nav-link active" %>
        </li>
            
        <li class="nav-item">
           <%= link_to "Add Albums" , new_album_path , class:"nav-link active" %>
        </li>

        <li class="nav-item">
           <%= link_to "Log Out" , destroy_user_session_path , method: :delete , class:"nav-link active" %>
        </li>
        <li class="nav-item">
           <%= link_to "Edit Profile" , edit_user_registration_path , class:"nav-link active" %>
        </li>


        <% else %>
        <li class="nav-item">
           <%= link_to "Sign Up" , new_user_registration_path , class:"nav-link active" %>
        </li>       
        <li class="nav-item">
           <%= link_to "Log In" , new_user_session_path , class:"nav-link active" %>
        </li>
        <% end %>

  

      </ul>

    </div>
  </div>
</nav>

app/views/home/index.html.erb
<div class="fw-bold "> Welcome </div>
<% name = current_user.present? ? current_user.email : '' %>

<h3><%=  name %></h3>
<div class="container">
    <% if current_user.present? %>
            <h2>
                <%= link_to "Go Add Some Albums", albums_path , class:"btn btn-primary"%>
            </h2>
        </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlbumApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </head>

  <body>
       <%= render "home/header" %>
       <p class="notice text-alert"><%= notice %></p>
       <p class="alert text-alert"><%= alert %></p>
    <%= yield %>
    
  </body>
</html>

app/views/photos/index.html.erb
<h1>Photos#index</h1>
<p>Find me in app/views/photos/index.html.erb</p>